User.create(email: "wginah@gmail.com", password: "password", first_name: "wellington", last_name: "G")
User.create(email: "robinchoii@gmail.com", password: "password", first_name: "robin", last_name: "C")
User.create(email: "justin@justin.com", password: "password", first_name: "justin", last_name: "Y")
User.create(email: "@wei.com", password: "password", first_name: "wei", last_name: "W")
User.create(email: "chris@chris.com", password: "password", first_name: "chris", last_name: "T")
User.create(email: "jimmy@jimmy.com", password: "password", first_name: "jimmy", last_name: "L")
User.create(email: "james@james.com", password: "password", first_name: "james", last_name: "B")
User.create(email: "alice@alice.com", password: "password", first_name: "alice", last_name: "M")
User.create(email: "jose@jose.com", password: "password", first_name: "jose", last_name: "T")
User.create(email: "aakash@aakash.com", password: "password", first_name: "aakash", last_name: "L")
User.create(email: "brian@brian.com", password: "password", first_name: "brian", last_name: "R")
User.create(email: "nathan@nathan.com", password: "password", first_name: "nathan", last_name: "M")
User.create(email: "stacie@stacie.com", password: "password", first_name: "stacie", last_name: "C")
User.create(email: "sarah@sarah.com", password: "password", first_name: "sarah", last_name: "A")
User.create(email: "mohammed@mohammed.com", password: "password", first_name: "mohammed", last_name: "S")
User.create(email: "alvin@alvin.com", password: "password", first_name: "alvin", last_name: "S")

